"""collection runtime proxy sessions notifications"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "20260916_0002"
down_revision = "20260914_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proxy_endpoints",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("scheme", sa.String(length=10), nullable=False),
        sa.Column("host", sa.String(length=253), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("credentials_encrypted", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("scheme = 'http'", name=op.f("ck_proxy_endpoints_scheme")),
        sa.CheckConstraint("port BETWEEN 1 AND 65535", name=op.f("ck_proxy_endpoints_port")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proxy_endpoints")),
    )
    op.create_index("ix_proxy_endpoints_created_id", "proxy_endpoints", ["created_at", "id"], unique=False)
    op.create_table(
        "telegram_settings",
        sa.Column("singleton", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("chat_id", sa.String(length=100), nullable=True),
        sa.Column("token_ciphertext", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("singleton", name=op.f("ck_telegram_settings_single_settings")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_settings")),
        sa.UniqueConstraint("singleton", name=op.f("uq_telegram_settings_singleton")),
    )
    op.create_table(
        "alert_events",
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("message", sa.String(length=300), nullable=False),
        sa.Column("related_alert_id", sa.Uuid(), nullable=True),
        sa.Column("occurrences", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("status IN ('active', 'resolved')", name=op.f("ck_alert_events_status")),
        sa.CheckConstraint("occurrences > 0", name=op.f("ck_alert_events_positive_occurrences")),
        sa.ForeignKeyConstraint(
            ["related_alert_id"], ["alert_events.id"], name=op.f("fk_alert_events_related_alert_id_alert_events")
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name=op.f("fk_alert_events_source_id_sources")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_events")),
    )
    op.create_index("ix_alert_events_created_id", "alert_events", ["created_at", "id"], unique=False)
    op.create_index(
        "uq_alert_events_source_active",
        "alert_events",
        ["source_id", "kind"],
        unique=True,
        postgresql_where=sa.text("status = 'active' AND source_id IS NOT NULL"),
    )
    op.create_index(
        "uq_alert_events_system_active",
        "alert_events",
        ["kind"],
        unique=True,
        postgresql_where=sa.text("status = 'active' AND source_id IS NULL"),
    )
    op.create_table(
        "login_attempts",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("route", sa.String(length=200), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("generation", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="queued", nullable=False),
        sa.Column("encrypted_qr", sa.LargeBinary(), nullable=True),
        sa.Column(
            "domains", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'qr_pending', 'verifying', 'authenticated', 'expired', "
            "'failed', 'cancelled', 'action_required')",
            name=op.f("ck_login_attempts_status"),
        ),
        sa.CheckConstraint("expires_at > created_at", name=op.f("ck_login_attempts_expiry")),
        sa.CheckConstraint("generation > 0", name=op.f("ck_login_attempts_generation")),
        sa.ForeignKeyConstraint(["admin_id"], ["admin_users.id"], name=op.f("fk_login_attempts_admin_id_admin_users")),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name=op.f("fk_login_attempts_source_id_sources")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
        sa.UniqueConstraint("admin_id", "route", "idempotency_key", name=op.f("uq_login_attempts_admin_id")),
    )
    op.create_index("ix_login_attempts_status_created", "login_attempts", ["status", "created_at"], unique=False)
    op.create_table(
        "proxy_checks",
        sa.Column("proxy_id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "result", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')", name=op.f("ck_proxy_checks_status")
        ),
        sa.ForeignKeyConstraint(["admin_id"], ["admin_users.id"], name=op.f("fk_proxy_checks_admin_id_admin_users")),
        sa.ForeignKeyConstraint(
            ["proxy_id"], ["proxy_endpoints.id"], name=op.f("fk_proxy_checks_proxy_id_proxy_endpoints")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proxy_checks")),
        sa.UniqueConstraint("admin_id", "proxy_id", "idempotency_key", name=op.f("uq_proxy_checks_admin_id")),
    )
    op.create_index("ix_proxy_checks_status_created", "proxy_checks", ["status", "created_at"], unique=False)
    op.create_table(
        "proxy_leases",
        sa.Column("proxy_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proxy_id"],
            ["proxy_endpoints.id"],
            name=op.f("fk_proxy_leases_proxy_id_proxy_endpoints"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name=op.f("fk_proxy_leases_source_id_sources")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proxy_leases")),
    )
    op.create_index("ix_proxy_leases_proxy_expiry", "proxy_leases", ["proxy_id", "expires_at"], unique=False)
    op.create_table(
        "proxy_source_health",
        sa.Column("proxy_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=40), nullable=True),
        sa.CheckConstraint(
            "status IN ('unknown', 'healthy', 'cooling_down', 'unavailable', 'disabled')",
            name=op.f("ck_proxy_source_health_status"),
        ),
        sa.ForeignKeyConstraint(
            ["proxy_id"],
            ["proxy_endpoints.id"],
            name=op.f("fk_proxy_source_health_proxy_id_proxy_endpoints"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name=op.f("fk_proxy_source_health_source_id_sources")),
        sa.PrimaryKeyConstraint("proxy_id", "source_id", name=op.f("pk_proxy_source_health")),
    )
    op.create_table(
        "source_egress_states",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("proxy_id", sa.Uuid(), nullable=True),
        sa.Column("egress_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=False),
        sa.Column("fallback_direct", sa.Boolean(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["proxy_id"], ["proxy_endpoints.id"], name=op.f("fk_source_egress_states_proxy_id_proxy_endpoints")
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name=op.f("fk_source_egress_states_source_id_sources")),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_source_egress_states")),
    )
    op.create_table(
        "source_sessions",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="unauthenticated", nullable=False),
        sa.Column("generation", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("encrypted_state", sa.LargeBinary(), nullable=True),
        sa.Column(
            "domains", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("egress_id", sa.String(length=100), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('unauthenticated', 'qr_pending', 'verifying', 'authenticated', 'expired', 'failed', 'revoked')",
            name=op.f("ck_source_sessions_status"),
        ),
        sa.CheckConstraint("generation >= 0", name=op.f("ck_source_sessions_generation")),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name=op.f("fk_source_sessions_source_id_sources")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_sessions")),
        sa.UniqueConstraint("source_id", name=op.f("uq_source_sessions_source_id")),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("alert_id", sa.Uuid(), nullable=True),
        sa.Column("admin_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("event_status", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "attempt_history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "event_status IN ('active', 'resolved', 'test')", name=op.f("ck_notification_deliveries_event_status")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sending', 'retrying', 'sent', 'failed', 'disabled', 'not_configured')",
            name=op.f("ck_notification_deliveries_status"),
        ),
        sa.CheckConstraint("attempts >= 0 AND attempts <= 5", name=op.f("ck_notification_deliveries_bounded_attempts")),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["admin_users.id"], name=op.f("fk_notification_deliveries_admin_id_admin_users")
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["alert_events.id"], name=op.f("fk_notification_deliveries_alert_id_alert_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint("alert_id", name=op.f("uq_notification_deliveries_alert_id")),
    )
    op.create_index(
        "ix_notification_deliveries_due", "notification_deliveries", ["status", "next_attempt_at"], unique=False
    )
    op.create_index("uq_notification_test_key", "notification_deliveries", ["admin_id", "idempotency_key"], unique=True)
    op.create_table(
        "source_runtimes",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="idle", nullable=False),
        sa.Column("generation", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("owner", sa.String(length=100), nullable=True),
        sa.Column("node_id", sa.String(length=100), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "restart_history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("restart_pending", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pause_reason", sa.Text(), nullable=True),
        sa.Column("last_run_id", sa.Uuid(), nullable=True),
        sa.Column("last_run_type", sa.String(length=20), nullable=True),
        sa.Column("recovery_scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_run_id"], ["crawl_runs.id"], name=op.f("fk_source_runtimes_last_run_id_crawl_runs")
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name=op.f("fk_source_runtimes_source_id_sources")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_runtimes")),
        sa.UniqueConstraint("source_id", name=op.f("uq_source_runtimes_source_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_runtimes")
    op.drop_index("uq_notification_test_key", table_name="notification_deliveries")
    op.drop_index("ix_notification_deliveries_due", table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_table("source_sessions")
    op.drop_table("source_egress_states")
    op.drop_table("proxy_source_health")
    op.drop_index("ix_proxy_leases_proxy_expiry", table_name="proxy_leases")
    op.drop_table("proxy_leases")
    op.drop_index("ix_proxy_checks_status_created", table_name="proxy_checks")
    op.drop_table("proxy_checks")
    op.drop_index("ix_login_attempts_status_created", table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_index(
        "uq_alert_events_system_active",
        table_name="alert_events",
        postgresql_where=sa.text("status = 'active' AND source_id IS NULL"),
    )
    op.drop_index(
        "uq_alert_events_source_active",
        table_name="alert_events",
        postgresql_where=sa.text("status = 'active' AND source_id IS NOT NULL"),
    )
    op.drop_index("ix_alert_events_created_id", table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_table("telegram_settings")
    op.drop_index("ix_proxy_endpoints_created_id", table_name="proxy_endpoints")
    op.drop_table("proxy_endpoints")
    # ### end Alembic commands ###
